In [1]:
#Bibliotecas
import pandas as pd
import numpy as np
import keyring
import cx_Oracle
import os
import glob
import math
import warnings
warnings.filterwarnings("ignore")

# Dados de Entrada

In [2]:
#Dados de entrada
#Pasta Comercial para ano 2023
pasta = r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023'

#Chaves Primárias
chaves_paulista = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\COMERCIAL\INDGER2.0_COM_Chaves.xlsx',sheet_name='Paulista')
chaves_piratininga = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\COMERCIAL\INDGER2.0_COM_Chaves.xlsx',sheet_name='Piratininga')
chaves_santacruz = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\COMERCIAL\INDGER2.0_COM_Chaves.xlsx',sheet_name='Santa Cruz')
chaves_rge = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\COMERCIAL\INDGER2.0_COM_Chaves.xlsx',sheet_name='RGE')
chaves_todas = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\COMERCIAL\INDGER2.0_COM_Chaves.xlsx',sheet_name='Todas')

#Selecionar pasta do mes de referência
pasta_mes = input('Insira o mês (dois dígitos):')
ano = input('Insira o ano (4 dígitos):')
if pasta_mes == '01':
    mes = '01'
    pasta_mes = '01 - Janeiro\*'
    pasta_mes_paulista = '01 - Janeiro'
    pasta_mes_piratininga = '01 - Janeiro'
    pasta_mes_santacruz = '01 - Janeiro'
    pasta_mes_rge = '01 - Janeiro'
    print(pasta_mes)
elif pasta_mes == '02':
    mes = '02'
    pasta_mes = '02 - Fevereiro\*'
    pasta_mes_paulista = '02 - Fevereiro'
    pasta_mes_piratininga = '02 - Fevereiro'
    pasta_mes_santacruz = '02 - Fevereiro'
    pasta_mes_rge = '02 - Fevereiro'
    print(pasta_mes)
elif pasta_mes == '03':
    mes = '03'
    pasta_mes = '03 - Março\*'
    pasta_mes_paulista = '03 - Março'
    pasta_mes_piratininga = '03 - Março'
    pasta_mes_santacruz = '03 - Março'
    pasta_mes_rge = '03 - Março'
    print(pasta_mes)
elif pasta_mes == '04':
    mes = '04'
    pasta_mes = '04 - Abril\*'
    pasta_mes_paulista = '04 - Abril'
    pasta_mes_piratininga = '04 - Abril'
    pasta_mes_santacruz = '04 - Abril'
    pasta_mes_rge = '04 - Abril'
    print(pasta_mes)
elif pasta_mes == '05':
    mes = '05'
    pasta_mes = '05 - Maio\*'
    pasta_mes_paulista = '05 - Maio'
    pasta_mes_piratininga = '05 - Maio'
    pasta_mes_santacruz = '05 - Maio'
    pasta_mes_rge = '05 - Maio'
    print(pasta_mes)
elif pasta_mes == '06':
    mes = '06'
    pasta_mes = '06 - Junho\*'
    pasta_mes_paulista = '06 - Junho'
    pasta_mes_piratininga = '06 - Junho'
    pasta_mes_santacruz = '06 - Junho'
    pasta_mes_rge = '06 - Junho'
    print(pasta_mes)
elif pasta_mes == '07':
    mes = '07'
    pasta_mes = '07 - Julho\*'
    pasta_mes_paulista = '07 - Julho'
    pasta_mes_piratininga = '07 - Julho'
    pasta_mes_santacruz = '07 - Julho'
    pasta_mes_rge = '07 - Julho'
    print(pasta_mes)
elif pasta_mes == '08':
    mes = '08'
    pasta_mes = '08 - Agosto\*'
    pasta_mes_paulista = '08 - Agosto'
    pasta_mes_piratininga = '08 - Agosto'
    pasta_mes_santacruz = '08 - Agosto'
    pasta_mes_rge = '08 - Agosto'
    print(pasta_mes)
elif pasta_mes == '09':
    mes = '09'
    pasta_mes = '09 - Setembro\*'
    pasta_mes_paulista = '09 - Setembro'
    pasta_mes_piratininga = '09 - Setembro'
    pasta_mes_santacruz = '09 - Setembro'
    pasta_mes_rge = '09 - Setembro'
    print(pasta_mes)
elif pasta_mes == '10':
    mes = '10'
    pasta_mes = '10 - Outubro\*'
    pasta_mes_paulista = '10 - Outubro'
    pasta_mes_piratininga = '10 - Outubro'
    pasta_mes_santacruz = '10 - Outubro'
    pasta_mes_rge = '10 - Outubro'
    print(pasta_mes)
elif pasta_mes == '11':
    mes = '11'
    pasta_mes = '11 - Novembro\*'
    pasta_mes_paulista = '11 - Novembro'
    pasta_mes_piratininga = '11 - Novembro'
    pasta_mes_santacruz = '11 - Novembro'
    pasta_mes_rge = '11 - Novembro'
    print(pasta_mes)
elif pasta_mes == '12':
    mes = '12'
    pasta_mes = '12 - Dezembro\*'
    pasta_mes_paulista = '12 - Dezembro'
    pasta_mes_piratininga = '12 - Dezembro'
    pasta_mes_santacruz = '12 - Dezembro'
    pasta_mes_rge = '12 - Dezembro'
    print(pasta_mes)
else:
    print('Mês Inválido')
    
#Pasta onde está os arquivos    
diretorio = os.path.join(pasta,pasta_mes)
arquivos = glob.glob(diretorio)

#Define o diretorio onde será salvo os arquivos consolidados
pasta_paulista = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\1 - Paulista\\2023\\{pasta_mes_paulista}\\2 - Arquivos Consolidados'
pasta_piratininga = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\2 - Piratininga\\2023\\{pasta_mes_piratininga}\\2 - Arquivos Consolidados'
pasta_santacruz = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\3 - Santa Cruz\\2023\\{pasta_mes_santacruz}\\2 - Arquivos Consolidados'
pasta_rge = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\4 - RGE\\2023\\{pasta_mes_rge}\\2 - Arquivos Consolidados'
pasta_paulista_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\1 - Paulista\\2023\\{pasta_mes_paulista}\\1 - Status'
pasta_piratininga_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\2 - Piratininga\\2023\\{pasta_mes_piratininga}\\1 - Status'
pasta_santacruz_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\3 - Santa Cruz\\2023\\{pasta_mes_santacruz}\\1 - Status'
pasta_rge_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\4 - RGE\\2023\\{pasta_mes_rge}\\1 - Status'

Insira o mês (dois dígitos):10
Insira o ano (4 dígitos):2023
10 - Outubro\*

In [3]:
#Colunas
colunas_comercial = ['COM_001','COM_002','COM_003','COM_004','COM_005','COM_006','COM_007','COM_008','COM_009','COM_010','COM_011','COM_012','COM_013','COM_014','COM_015','COM_016','COM_017','COM_018','COM_019','COM_020','COM_021','COM_022','COM_023','COM_024','COM_025','COM_026','COM_027','COM_028','COM_029','COM_030','COM_031','COM_032','COM_033','COM_034','COM_035','COM_036','COM_037','COM_038','COM_039','COM_040','COM_041','COM_042','COM_043','COM_044','COM_045','COM_046','COM_047','COM_048','COM_049','COM_050','COM_051','COM_052','COM_053','COM_054','COM_055','COM_056','COM_057','COM_058','COM_059']
colunas_campos = ['COM_005','COM_006','COM_007','COM_008','COM_009','COM_010','COM_011','COM_012','COM_013','COM_014','COM_015','COM_016','COM_017','COM_018','COM_019','COM_020','COM_021','COM_022','COM_023','COM_024','COM_025','COM_026','COM_027','COM_028','COM_029','COM_030','COM_031','COM_032','COM_033','COM_034','COM_035','COM_036','COM_037','COM_038','COM_039','COM_040','COM_041','COM_042','COM_043','COM_044','COM_045','COM_046','COM_047','COM_048','COM_049','COM_050','COM_051','COM_052','COM_053','COM_054','COM_055','COM_056','COM_057','COM_058','COM_059']
colunas_chaves = ['COM_001','COM_002','COM_003','COM_004']
colunas_integer = ['COM_005','COM_006','COM_007','COM_008','COM_009','COM_010','COM_011','COM_012','COM_013','COM_014','COM_015','COM_016','COM_017','COM_018','COM_019','COM_020','COM_021','COM_022','COM_023','COM_024','COM_025','COM_026','COM_027','COM_028','COM_029','COM_030','COM_031','COM_032','COM_033','COM_034','COM_035','COM_036','COM_037','COM_038','COM_041','COM_042','COM_043','COM_044','COM_045','COM_046','COM_049','COM_050','COM_051','COM_052','COM_053','COM_054','COM_055','COM_056','COM_057','COM_058']
colunas_float = ['COM_039','COM_040','COM_047','COM_048','COM_059']
colunas_string = ['COM_002']
colunas_djc1 = ['COM_001','COM_002','COM_003','COM_004','COM_041']
colunas_djc2 = ['COM_001','COM_002','COM_003','COM_004','COM_037','COM_038','COM_039','COM_040']
colunas_djc3 = ['COM_001','COM_002','COM_003','COM_004','COM_042','COM_043','COM_044','COM_045','COM_046','COM_047','COM_048','COM_049','COM_050']
colunas_djm = ['COM_001','COM_002','COM_003','COM_004','COM_029','COM_030','COM_031','COM_032','COM_033','COM_034','COM_035','COM_036']
colunas_dpca1 = ['COM_001','COM_002','COM_003','COM_004','COM_037','COM_038','COM_039','COM_040']
colunas_dpca2 = ['COM_001','COM_002','COM_003','COM_004','COM_042','COM_043','COM_044','COM_045','COM_046','COM_047','COM_048','COM_049','COM_050']
colunas_dpcl = ['COM_001','COM_002','COM_003','COM_004','COM_041']
colunas_dpoc = ['COM_001','COM_002','COM_003','COM_004','COM_029','COM_030','COM_031','COM_032','COM_033','COM_034','COM_035','COM_036']
colunas_dro = ['COM_001','COM_002','COM_003','COM_004','COM_029','COM_030','COM_031','COM_032','COM_033','COM_034','COM_035','COM_036']
colunas_drs1 = ['COM_001','COM_002','COM_003','COM_004','COM_042','COM_043','COM_044','COM_045','COM_046','COM_047','COM_048','COM_049','COM_050']
colunas_drs2 = ['COM_001','COM_002','COM_003','COM_004','COM_037','COM_038','COM_039','COM_040']
colunas_drs3 = ['COM_001','COM_002','COM_003','COM_004','COM_041']
colunas_rccf1 = ['COM_001','COM_002','COM_003','COM_004','COM_005','COM_006','COM_007','COM_015']
colunas_rccf2 = ['COM_001','COM_002','COM_003','COM_004','COM_008','COM_013','COM_014','COM_018','COM_019','COM_020']
colunas_rccf3 = ['COM_001','COM_002','COM_003','COM_004','COM_009','COM_010','COM_011','COM_012','COM_016','COM_017','COM_021','COM_022','COM_023','COM_024','COM_025','COM_026','COM_027','COM_028']
colunas_rcre = ['COM_001','COM_002','COM_003','COM_004','COM_051','COM_052','COM_053','COM_054','COM_055']
colunas_rcrr = ['COM_001','COM_002','COM_003','COM_004','COM_056','COM_057','COM_058','COM_059']
listas_arquivos = ['COM_DJC1_KarinaVenezian','COM_DJC2_VanessaCandreva','COM_DJC3_VanessaCarine','COM_DJM_AdrianoAlves','COM_DPCA1_SamuelPaschoini','COM_DPCA2_GelikaMelo','COM_DPCL_JohanWillian','COM_DPOC_LuizClaudio','COM_DRO_DiegoOliveira','COM_DRS1_AmandaTegner','COM_DRS2_DanielaWilhelm','COM_DRS3_JoséDieterich','COM_RCCF1_DenisGatti','COM_RCCF2_JanaynaCarvalho','COM_RCCF3_ThainaCristine','COM_RCRE_TalesFonteBoa','COM_RCRR_MatheusMaciel']

#Layout com todas as colunas
layout_comercial_colunas = pd.DataFrame(data = [],columns = colunas_comercial)

#Tabela Comercial
tabela_comercial = []

#Duplicadas
df_duplicadas = pd.DataFrame(data = [],columns = colunas_comercial)

#Total de arquivos esperados na pasta
arquivos_total = 20

#Quantidade de arquivos submetidos
arquivos_submetidos = len(arquivos)

#Arquivos faltantes
print('Arquivos faltantes:',(arquivos_total-arquivos_submetidos))

#Flag para mostrar os arquivos faltantes
flag_faltantes = []

#Leitura dos arquivos
for arquivo in arquivos:
    try:
        #Lê o arquivo na pasta
        df_comercial = pd.read_excel(arquivo,sheet_name='COMERCIAL',decimal=',')
        
        #Define o mês e o ano
        linhas_df_comercial = range(len(df_comercial.index))
        df_comercial['COM_003'] = df_comercial['COM_003'].astype('str')
        for linha in linhas_df_comercial:
            df_comercial.loc[linha,'COM_003'] = df_comercial.loc[linha,'COM_003'].zfill(2)
        df_comercial['COM_004'] = ano
        
        #Valida se foi enviado algum mês fora do mês de referência
        flag_mes = 0
        for linha in linhas_df_comercial:
            if df_comercial.loc[linha,'COM_003'] != mes:
                flag_mes = 1
        if flag_mes != 0:
            print('MÊS INCORRETO!!!', arquivo)
            
        #Valida se foi enviado algum código da distribuidora incorreto
        flag_distribuidora = 0
        for linha in linhas_df_comercial:
            if df_comercial.loc[linha,'COM_001'] not in [63,2937,69,396]:
                flag_distribuidora = 1
        if flag_distribuidora != 0:
            print('DISTRIBUIDORA INCORRETA!!!', arquivo)
        
        #Converte as chave para string
        for coluna in colunas_chaves:
            df_comercial[coluna] = df_comercial[coluna].astype('str')
        
        
        #Empilha as chaves primárias duplicadas
        if df_comercial.duplicated(subset=['COM_001','COM_002','COM_003','COM_004']).any() == False:
            pass
        else:
            duplicadas = df_comercial[df_comercial.duplicated(subset=['COM_001','COM_002','COM_003','COM_004'],keep=False)]
            df_duplicadas = df_duplicadas.append(duplicadas,ignore_index=True)
            
        
        #Empilha todos os arquivos
        layout_comercial_colunas = layout_comercial_colunas.append(df_comercial,ignore_index=True)
        
        #Validação de colunas dos arquivos
        if 'COM_DJC1_' in arquivo:
            df_comercial.columns == colunas_djc1
            flag_faltantes.append('COM_DJC1_KarinaVenezian')
            print(arquivo)
        elif 'COM_DJC2_' in arquivo:
            df_comercial.columns == colunas_djc2
            flag_faltantes.append('COM_DJC2_VanessaCandreva')
            print(arquivo)
        elif 'COM_DJC3_' in arquivo:
            df_comercial.columns == colunas_djc3
            flag_faltantes.append('COM_DJC3_VanessaCarine')
            print(arquivo)
        elif 'COM_DJM_' in arquivo:
            df_comercial.columns == colunas_djm
            flag_faltantes.append('COM_DJM_AdrianoAlves')
            print(arquivo)
        elif 'COM_DPCA1_' in arquivo:
            df_comercial.columns == colunas_dpca1
            flag_faltantes.append('COM_DPCA1_SamuelPaschoini')
            print(arquivo)
        elif 'COM_DPCA2_' in arquivo:
            df_comercial.columns == colunas_dpca2
            flag_faltantes.append('COM_DPCA2_GelikaMelo')
            print(arquivo)
        elif 'COM_DPCL_' in arquivo:
            df_comercial.columns == colunas_dpcl
            flag_faltantes.append('COM_DPCL_JohanWillian')
            print(arquivo)
        elif 'COM_DPOC_' in arquivo:
            df_comercial.columns == colunas_dpoc
            flag_faltantes.append('COM_DPOC_LuizClaudio')
            print(arquivo)
        elif 'COM_DRO_' in arquivo:
            df_comercial.columns == colunas_dro
            flag_faltantes.append('COM_DRO_DiegoOliveira')
            print(arquivo)
        elif 'COM_DRS1_' in arquivo:
            df_comercial.columns == colunas_drs1
            flag_faltantes.append('COM_DRS1_AmandaTegner')
            print(arquivo)
        elif 'COM_DRS2_' in arquivo:
            df_comercial.columns == colunas_drs2
            flag_faltantes.append('COM_DRS2_DanielaWilhelm')
            print(arquivo)
        elif 'COM_DRS3_' in arquivo:
            df_comercial.columns == colunas_drs3
            flag_faltantes.append('COM_DRS3_JoséDieterich')
            print(arquivo)
        elif 'COM_RCCF1_' in arquivo:
            df_comercial.columns == colunas_rccf1
            flag_faltantes.append('COM_RCCF1_DenisGatti')
            print(arquivo)
        elif 'COM_RCCF2_' in arquivo:
            df_comercial.columns == colunas_rccf2
            flag_faltantes.append('COM_RCCF2_JanaynaCarvalho')
            print(arquivo)
        elif 'COM_RCCF3_' in arquivo:
            df_comercial.columns == colunas_rccf3
            flag_faltantes.append('COM_RCCF3_ThainaCristine')
            print(arquivo)
        elif 'COM_RCRE_' in arquivo:
            df_comercial.columns == colunas_rcre
            flag_faltantes.append('COM_RCRE_TalesFonteBoa')
            print(arquivo)
        elif 'COM_RCRR_' in arquivo:
            df_comercial.columns == colunas_rcrr
            flag_faltantes.append('COM_RCRR_MatheusMaciel')
            print(arquivo)
        else:
            print('Arquivo com colunas divergentes',arquivo)
    
        
    except Exception as err:
        print('Arquivo com erro:',err, arquivo)
        
#Exclui as linhas duplicadas
df_duplicadas = df_duplicadas.drop_duplicates(ignore_index=True)

#Compara se há chaves primárias duplicadas
if df_duplicadas.duplicated(subset=['COM_001','COM_002','COM_003','COM_004']).any() == False:
    print('Não há chaves duplicadas')
else:
    print('Há chaves duplicadas', arquivo)
    #Mostra as chaves duplicadas
    df_duplicadas = df_duplicadas[df_duplicadas.duplicated(subset=['COM_001','COM_002','COM_003','COM_004'],keep=False)]
    df_duplicadas.to_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Erros Duplicadas\duplicadas_comercial.xlsx')
    display(df_duplicadas)
    
    
#Reporta os arquivos faltantes
for lista_arquivos in listas_arquivos:
    if lista_arquivos not in flag_faltantes:
        print(f'Arquivo faltante: {lista_arquivos}')

Arquivos faltantes: 0
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DJC1_KarinaVenezian.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DJC2_Piratininga_VanessaCandreva_10.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DJC2_SantaCruz_VanessaCandreva_10.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DJC3_VanessaCarine_10_Pira.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DJC3_VanessaCarine_10_Santa.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DJM_OUT23_Piratininga_AdrianoAlves.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DJM_OUT23_SantaCruz_AdrianoAlves.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DPCA1_SamuelPaschoini_10_2023.xlsb
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DPCA2_GelikaMelo.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DPCL_JohanWillian.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DPOC_LuizClaudio_10_2023.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DRO_CarlosEduardoSpreng.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DRS1_AmandaTegner.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DRS2_DanielaWilhelm.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_DRS3_JoséDieterich.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_RCCF1_DenisGatti_112023.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_RCCF2_JanaynaCarvalho.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_RCCF3_ThainaCristine.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_RCRE_TalesFonteBoa_102023.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\COMERCIAL\2023\10 - Outubro\COM_RCRR_MatheusMaciel.xlsx
Não há chaves duplicadas

In [4]:
#Dropa as linhas duplicadas
layout_comercial_colunas = layout_comercial_colunas.drop_duplicates(ignore_index=True)

#Empilha os dataframe
tabela_comercial = layout_comercial_colunas.groupby(['COM_001','COM_002','COM_003','COM_004'],as_index=False).max()
print('Dados empilhados')

Dados empilhados

In [5]:
#tabela_comercial.to_excel(r'C:\Users\2018459\OneDrive - CPFL Energia S A\Documentos\Projetos\2023\INDGER 2.0\MUNICIPIO.xlsx')

In [6]:
#Define o mês e o ano
linhas = range(len(tabela_comercial.index))
tabela_comercial['COM_003'] = tabela_comercial['COM_003'].astype('str')
for linha in linhas:
    tabela_comercial.loc[linha,'COM_003'] = tabela_comercial.loc[linha,'COM_003'].zfill(2)
tabela_comercial['COM_004'] = ano

In [7]:
display(tabela_comercial)

,COM_001,COM_002,COM_003,COM_004,COM_005,COM_006,COM_007,COM_008,COM_009,COM_010,...,COM_050,COM_051,COM_052,COM_053,COM_054,COM_055,COM_056,COM_057,COM_058,COM_059
0,2937,3501152,10,2023,6042.0,5841.0,5892.0,1.0,4,0,...,0,5.0,0.0,0.0,0.0,0.0,0,5,0,0.00
1,2937,3502754,10,2023,10097.0,9764.0,9879.0,2.0,9,0,...,0,42.0,1.0,0.0,0.0,0.0,0,218,4,0.00
2,2937,3502903,10,2023,23564.0,23042.0,23212.0,10.0,214,0,...,0,106.0,26.0,4.0,5.0,0.0,0,18,0,0.00
3,2937,3507001,10,2023,34245.0,33390.0,33696.0,2.0,91,0,...,0,239.0,15.0,2.0,2.0,0.0,1,229,3,0.00
4,2937,3509601,10,2023,32278.0,31149.0,31372.0,1.0,53,0,...,0,228.0,23.0,7.0,8.0,0.0,2,931,4,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693,69,3555505,10,2023,2288.0,2244.0,2248.0,2.0,4,0,...,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0.00
694,69,3557204,10,2023,5644.0,5510.0,5512.0,1.0,16,0,...,0,3.0,3.0,0.0,2.0,0.0,0,69,0,0.00
695,69,4102703,10,2023,1256.0,1239.0,1239.0,2.0,1,0,...,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0.00
696,69,4111803,10,2023,17615.0,17115.0,17170.0,2.0,43,0,...,0,8.0,4.0,0.0,1.0,0.0,0,180,0,0.00
697,69,4121802,10,2023,6064.0,5992.0,5999.0,1.0,16,0,...,0,1.0,1.0,0.0,0.0,0.0,0,13,0,10.23

In [8]:
#Verifica se há chaves nulas
tabela_comercial = tabela_comercial.replace('nan',np.nan)

for coluna in colunas_chaves:
    if tabela_comercial[coluna].isnull().any() == True:
        print('Existe Chave Primária Nula: ',coluna)

In [9]:
#Define o mês e o ano das Chaves Primárias
chaves_paulista['COM_003'] = mes
chaves_piratininga['COM_003'] = mes
chaves_santacruz['COM_003'] = mes
chaves_rge['COM_003'] = mes
chaves_paulista['COM_004'] = ano
chaves_piratininga['COM_004'] = ano
chaves_santacruz['COM_004'] = ano
chaves_rge['COM_004'] = ano

#Seleciona somente as colunas das chaves primárias
chaves_paulista = chaves_paulista[['COM_001','COM_002','COM_003','COM_004']]
chaves_piratininga = chaves_piratininga[['COM_001','COM_002','COM_003','COM_004']]
chaves_santacruz = chaves_santacruz[['COM_001','COM_002','COM_003','COM_004']]
chaves_rge = chaves_rge[['COM_001','COM_002','COM_003','COM_004']]

# Validação dos Dados

In [10]:
# Validação de número negativo
try:
    for coluna in colunas_campos:
        if tabela_comercial[coluna].min() < 0:
            print('Temos dados negativos:',coluna)
except:
    print('Erro na coluna:',coluna)

In [11]:
#Separa a tabela por distribuidora para verificar se há colunas nulas
df_comercial_paulista = tabela_comercial.loc[tabela_comercial['COM_001'] == '63']
df_comercial_piratininga = tabela_comercial.loc[tabela_comercial['COM_001'] == '2937']
df_comercial_santacruz = tabela_comercial.loc[tabela_comercial['COM_001'] == '69']
df_comercial_rge = tabela_comercial.loc[tabela_comercial['COM_001'] == '396']

In [12]:
# PAULISTA 
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_paulista=[]
for coluna in df_comercial_paulista.columns:
    if df_comercial_paulista[coluna].isnull().all():
        indicadores_nao_recebidos_paulista.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_comercial, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_paulista))

status_recebimento_comercial_paulista = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_comercial_paulista.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_comercial_paulista = status_recebimento_comercial_paulista.reindex(columns = ['Indicador','Status'])
status_recebimento_comercial_paulista.insert(loc=2,column='Distribuidora',value='Paulista')
status_recebimento_comercial_paulista.to_excel(os.path.join(pasta_paulista_status,'status_recebimento_comercial_paulista.xlsx'))
status_recebimento_comercial_paulista

   Indicador  Status Distribuidora
0    COM_001    True      Paulista
1    COM_002    True      Paulista
2    COM_003    True      Paulista
3    COM_004    True      Paulista
4    COM_005    True      Paulista
5    COM_006    True      Paulista
6    COM_007    True      Paulista
7    COM_008    True      Paulista
8    COM_009    True      Paulista
9    COM_010    True      Paulista
10   COM_011    True      Paulista
11   COM_012    True      Paulista
12   COM_013    True      Paulista
13   COM_014    True      Paulista
14   COM_015    True      Paulista
15   COM_016    True      Paulista
16   COM_017    True      Paulista
17   COM_018    True      Paulista
18   COM_019    True      Paulista
19   COM_020    True      Paulista
20   COM_021    True      Paulista
21   COM_022    True      Paulista
22   COM_023    True      Paulista
23   COM_024    True      Paulista
24   COM_025    True      Paulista
25   COM_026    True      Paulista
26   COM_027    True      Paulista
27   COM_028   False      Paulista
28   COM_029    True      Paulista
29   COM_030    True      Paulista
30   COM_031    True      Paulista
31   COM_032    True      Paulista
32   COM_033    True      Paulista
33   COM_034    True      Paulista
34   COM_035    True      Paulista
35   COM_036    True      Paulista
36   COM_037    True      Paulista
37   COM_038    True      Paulista
38   COM_039    True      Paulista
39   COM_040    True      Paulista
40   COM_041    True      Paulista
41   COM_042    True      Paulista
42   COM_043    True      Paulista
43   COM_044    True      Paulista
44   COM_045    True      Paulista
45   COM_046    True      Paulista
46   COM_047    True      Paulista
47   COM_048    True      Paulista
48   COM_049    True      Paulista
49   COM_050    True      Paulista
50   COM_051    True      Paulista
51   COM_052    True      Paulista
52   COM_053    True      Paulista
53   COM_054    True      Paulista
54   COM_055    True      Paulista
55   COM_056    True      Paulista
56   COM_057    True      Paulista
57   COM_058    True      Paulista
58   COM_059    True      Paulista

In [13]:
# Piratininga 
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_piratininga=[]
for coluna in df_comercial_piratininga.columns:
    if df_comercial_piratininga[coluna].isnull().all():
        indicadores_nao_recebidos_piratininga.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_comercial, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_piratininga))

status_recebimento_comercial_piratininga = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_comercial_piratininga.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_comercial_piratininga = status_recebimento_comercial_piratininga.reindex(columns = ['Indicador','Status'])
status_recebimento_comercial_piratininga.insert(loc=2,column='Distribuidora',value='Piratininga')
status_recebimento_comercial_piratininga.to_excel(os.path.join(pasta_piratininga_status,'status_recebimento_comercial_piratininga.xlsx'))
status_recebimento_comercial_piratininga

   Indicador  Status Distribuidora
0    COM_001    True   Piratininga
1    COM_002    True   Piratininga
2    COM_003    True   Piratininga
3    COM_004    True   Piratininga
4    COM_005    True   Piratininga
5    COM_006    True   Piratininga
6    COM_007    True   Piratininga
7    COM_008    True   Piratininga
8    COM_009    True   Piratininga
9    COM_010    True   Piratininga
10   COM_011    True   Piratininga
11   COM_012    True   Piratininga
12   COM_013    True   Piratininga
13   COM_014    True   Piratininga
14   COM_015    True   Piratininga
15   COM_016    True   Piratininga
16   COM_017    True   Piratininga
17   COM_018    True   Piratininga
18   COM_019    True   Piratininga
19   COM_020    True   Piratininga
20   COM_021    True   Piratininga
21   COM_022    True   Piratininga
22   COM_023    True   Piratininga
23   COM_024    True   Piratininga
24   COM_025    True   Piratininga
25   COM_026    True   Piratininga
26   COM_027    True   Piratininga
27   COM_028   False   Piratininga
28   COM_029    True   Piratininga
29   COM_030    True   Piratininga
30   COM_031    True   Piratininga
31   COM_032    True   Piratininga
32   COM_033    True   Piratininga
33   COM_034    True   Piratininga
34   COM_035    True   Piratininga
35   COM_036    True   Piratininga
36   COM_037    True   Piratininga
37   COM_038    True   Piratininga
38   COM_039    True   Piratininga
39   COM_040    True   Piratininga
40   COM_041    True   Piratininga
41   COM_042    True   Piratininga
42   COM_043    True   Piratininga
43   COM_044    True   Piratininga
44   COM_045    True   Piratininga
45   COM_046    True   Piratininga
46   COM_047    True   Piratininga
47   COM_048    True   Piratininga
48   COM_049    True   Piratininga
49   COM_050    True   Piratininga
50   COM_051    True   Piratininga
51   COM_052    True   Piratininga
52   COM_053    True   Piratininga
53   COM_054    True   Piratininga
54   COM_055    True   Piratininga
55   COM_056    True   Piratininga
56   COM_057    True   Piratininga
57   COM_058    True   Piratininga
58   COM_059    True   Piratininga

In [14]:
# Santa Cruz 
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_santacruz=[]
for coluna in df_comercial_santacruz.columns:
    if df_comercial_santacruz[coluna].isnull().all():
        indicadores_nao_recebidos_santacruz.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_comercial, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_santacruz))

status_recebimento_comercial_santacruz = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_comercial_santacruz.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_comercial_santacruz = status_recebimento_comercial_santacruz.reindex(columns = ['Indicador','Status'])
status_recebimento_comercial_santacruz.insert(loc=2,column='Distribuidora',value='Santa Cruz')
status_recebimento_comercial_santacruz.to_excel(os.path.join(pasta_santacruz_status,'status_recebimento_comercial_santacruz.xlsx'))
status_recebimento_comercial_santacruz

   Indicador  Status Distribuidora
0    COM_001    True    Santa Cruz
1    COM_002    True    Santa Cruz
2    COM_003    True    Santa Cruz
3    COM_004    True    Santa Cruz
4    COM_005    True    Santa Cruz
5    COM_006    True    Santa Cruz
6    COM_007    True    Santa Cruz
7    COM_008    True    Santa Cruz
8    COM_009    True    Santa Cruz
9    COM_010    True    Santa Cruz
10   COM_011    True    Santa Cruz
11   COM_012    True    Santa Cruz
12   COM_013    True    Santa Cruz
13   COM_014    True    Santa Cruz
14   COM_015    True    Santa Cruz
15   COM_016    True    Santa Cruz
16   COM_017    True    Santa Cruz
17   COM_018    True    Santa Cruz
18   COM_019    True    Santa Cruz
19   COM_020    True    Santa Cruz
20   COM_021    True    Santa Cruz
21   COM_022    True    Santa Cruz
22   COM_023    True    Santa Cruz
23   COM_024    True    Santa Cruz
24   COM_025    True    Santa Cruz
25   COM_026    True    Santa Cruz
26   COM_027    True    Santa Cruz
27   COM_028    True    Santa Cruz
28   COM_029    True    Santa Cruz
29   COM_030    True    Santa Cruz
30   COM_031    True    Santa Cruz
31   COM_032    True    Santa Cruz
32   COM_033    True    Santa Cruz
33   COM_034    True    Santa Cruz
34   COM_035    True    Santa Cruz
35   COM_036    True    Santa Cruz
36   COM_037    True    Santa Cruz
37   COM_038    True    Santa Cruz
38   COM_039    True    Santa Cruz
39   COM_040    True    Santa Cruz
40   COM_041    True    Santa Cruz
41   COM_042    True    Santa Cruz
42   COM_043    True    Santa Cruz
43   COM_044    True    Santa Cruz
44   COM_045    True    Santa Cruz
45   COM_046    True    Santa Cruz
46   COM_047    True    Santa Cruz
47   COM_048    True    Santa Cruz
48   COM_049    True    Santa Cruz
49   COM_050    True    Santa Cruz
50   COM_051    True    Santa Cruz
51   COM_052    True    Santa Cruz
52   COM_053    True    Santa Cruz
53   COM_054    True    Santa Cruz
54   COM_055    True    Santa Cruz
55   COM_056    True    Santa Cruz
56   COM_057    True    Santa Cruz
57   COM_058    True    Santa Cruz
58   COM_059    True    Santa Cruz

In [15]:
# RGE
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_rge=[]
for coluna in df_comercial_rge.columns:
    if df_comercial_rge[coluna].isnull().all():
        indicadores_nao_recebidos_rge.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_comercial, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_rge))

status_recebimento_comercial_rge = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_comercial_rge.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_comercial_rge = status_recebimento_comercial_rge.reindex(columns = ['Indicador','Status'])
status_recebimento_comercial_rge.insert(loc=2,column='Distribuidora',value='RGE')
status_recebimento_comercial_rge.to_excel(os.path.join(pasta_rge_status,'status_recebimento_comercial_rge.xlsx'))
status_recebimento_comercial_rge

   Indicador  Status Distribuidora
0    COM_001    True           RGE
1    COM_002    True           RGE
2    COM_003    True           RGE
3    COM_004    True           RGE
4    COM_005    True           RGE
5    COM_006    True           RGE
6    COM_007    True           RGE
7    COM_008    True           RGE
8    COM_009    True           RGE
9    COM_010    True           RGE
10   COM_011    True           RGE
11   COM_012    True           RGE
12   COM_013    True           RGE
13   COM_014    True           RGE
14   COM_015    True           RGE
15   COM_016    True           RGE
16   COM_017    True           RGE
17   COM_018    True           RGE
18   COM_019    True           RGE
19   COM_020    True           RGE
20   COM_021    True           RGE
21   COM_022    True           RGE
22   COM_023    True           RGE
23   COM_024    True           RGE
24   COM_025    True           RGE
25   COM_026    True           RGE
26   COM_027    True           RGE
27   COM_028    True           RGE
28   COM_029    True           RGE
29   COM_030    True           RGE
30   COM_031    True           RGE
31   COM_032    True           RGE
32   COM_033    True           RGE
33   COM_034    True           RGE
34   COM_035    True           RGE
35   COM_036    True           RGE
36   COM_037    True           RGE
37   COM_038    True           RGE
38   COM_039    True           RGE
39   COM_040    True           RGE
40   COM_041    True           RGE
41   COM_042    True           RGE
42   COM_043    True           RGE
43   COM_044    True           RGE
44   COM_045    True           RGE
45   COM_046    True           RGE
46   COM_047    True           RGE
47   COM_048    True           RGE
48   COM_049    True           RGE
49   COM_050    True           RGE
50   COM_051    True           RGE
51   COM_052    True           RGE
52   COM_053    True           RGE
53   COM_054    True           RGE
54   COM_055    True           RGE
55   COM_056    True           RGE
56   COM_057    True           RGE
57   COM_058    True           RGE
58   COM_059    True           RGE

In [16]:
#Separa a tabela por distribuidora para cruzar com as chaves primárias
df_comercial_paulista = tabela_comercial.loc[tabela_comercial['COM_001'] == '63']
df_comercial_piratininga = tabela_comercial.loc[tabela_comercial['COM_001'] == '2937']
df_comercial_santacruz = tabela_comercial.loc[tabela_comercial['COM_001'] == '69']
df_comercial_rge = tabela_comercial.loc[tabela_comercial['COM_001'] == '396']

In [17]:
#Converte as chave para string
for coluna in colunas_chaves:
    chaves_paulista[coluna] = chaves_paulista[coluna].astype('str')

#Converte as chave para string
for coluna in colunas_chaves:
    chaves_piratininga[coluna] = chaves_piratininga[coluna].astype('str')

#Converte as chave para string
for coluna in colunas_chaves:
    chaves_santacruz[coluna] = chaves_santacruz[coluna].astype('str')

#Converte as chave para string
for coluna in colunas_chaves:
    chaves_rge[coluna] = chaves_rge[coluna].astype('str')

In [18]:
#Cruza as Chaves Primárias com os arquivos carregados
df_comercial_paulista_join = chaves_paulista.merge(df_comercial_paulista,on=['COM_001','COM_002','COM_003','COM_004'],how='left') 
df_comercial_piratininga_join = chaves_piratininga.merge(df_comercial_piratininga,on=['COM_001','COM_002','COM_003','COM_004'],how='left') 
df_comercial_santacruz_join = chaves_santacruz.merge(df_comercial_santacruz,on=['COM_001','COM_002','COM_003','COM_004'],how='left') 
df_comercial_rge_join = chaves_rge.merge(df_comercial_rge,on=['COM_001','COM_002','COM_003','COM_004'],how='left')

In [19]:
#Possibilidade de desenvolver as celulas com valores NaN

# Tratamento, Limpeza e Conversão

In [20]:
#Tratamento, Limpeza e Conversão do tipo do dado
#Paulista
#Conversão do Código da distribuidora para o CNPJ
df_comercial_paulista_join['COM_001'] = df_comercial_paulista_join['COM_001'].replace('63','33050196000188')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_comercial_paulista_join[coluna_integer] = df_comercial_paulista_join[coluna_integer].replace(np.nan,0).astype('int')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_comercial_paulista_join[coluna_float] = df_comercial_paulista_join[coluna_float].replace(np.nan,0).astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)

Colunas integer convertidas:  COM_005
Colunas integer convertidas:  COM_006
Colunas integer convertidas:  COM_007
Colunas integer convertidas:  COM_008
Colunas integer convertidas:  COM_009
Colunas integer convertidas:  COM_010
Colunas integer convertidas:  COM_011
Colunas integer convertidas:  COM_012
Colunas integer convertidas:  COM_013
Colunas integer convertidas:  COM_014
Colunas integer convertidas:  COM_015
Colunas integer convertidas:  COM_016
Colunas integer convertidas:  COM_017
Colunas integer convertidas:  COM_018
Colunas integer convertidas:  COM_019
Colunas integer convertidas:  COM_020
Colunas integer convertidas:  COM_021
Colunas integer convertidas:  COM_022
Colunas integer convertidas:  COM_023
Colunas integer convertidas:  COM_024
Colunas integer convertidas:  COM_025
Colunas integer convertidas:  COM_026
Colunas integer convertidas:  COM_027
Colunas integer convertidas:  COM_028
Colunas integer convertidas:  COM_029
Colunas integer convertidas:  COM_030
Colunas integer convertidas:  COM_031
Colunas integer convertidas:  COM_032
Colunas integer convertidas:  COM_033
Colunas integer convertidas:  COM_034
Colunas integer convertidas:  COM_035
Colunas integer convertidas:  COM_036
Colunas integer convertidas:  COM_037
Colunas integer convertidas:  COM_038
Colunas integer convertidas:  COM_041
Colunas integer convertidas:  COM_042
Colunas integer convertidas:  COM_043
Colunas integer convertidas:  COM_044
Colunas integer convertidas:  COM_045
Colunas integer convertidas:  COM_046
Colunas integer convertidas:  COM_049
Colunas integer convertidas:  COM_050
Colunas integer convertidas:  COM_051
Colunas integer convertidas:  COM_052
Colunas integer convertidas:  COM_053
Colunas integer convertidas:  COM_054
Colunas integer convertidas:  COM_055
Colunas integer convertidas:  COM_056
Colunas integer convertidas:  COM_057
Colunas integer convertidas:  COM_058
Colunas float convertidas:  COM_039
Colunas float convertidas:  COM_040
Colunas float convertidas:  COM_047
Colunas float convertidas:  COM_048
Colunas float convertidas:  COM_059

In [21]:
#Tratamento, Limpeza e Conversão do tipo do dado
#Piratininga
#Conversão do Código da distribuidora para o CNPJ
df_comercial_piratininga_join['COM_001'] = df_comercial_piratininga_join['COM_001'].replace('2937','04172213000151')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_comercial_piratininga_join[coluna_integer] = df_comercial_piratininga_join[coluna_integer].replace(np.nan,0).astype('int')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_comercial_piratininga_join[coluna_float] = df_comercial_piratininga_join[coluna_float].replace(np.nan,0).astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)

Colunas integer convertidas:  COM_005
Colunas integer convertidas:  COM_006
Colunas integer convertidas:  COM_007
Colunas integer convertidas:  COM_008
Colunas integer convertidas:  COM_009
Colunas integer convertidas:  COM_010
Colunas integer convertidas:  COM_011
Colunas integer convertidas:  COM_012
Colunas integer convertidas:  COM_013
Colunas integer convertidas:  COM_014
Colunas integer convertidas:  COM_015
Colunas integer convertidas:  COM_016
Colunas integer convertidas:  COM_017
Colunas integer convertidas:  COM_018
Colunas integer convertidas:  COM_019
Colunas integer convertidas:  COM_020
Colunas integer convertidas:  COM_021
Colunas integer convertidas:  COM_022
Colunas integer convertidas:  COM_023
Colunas integer convertidas:  COM_024
Colunas integer convertidas:  COM_025
Colunas integer convertidas:  COM_026
Colunas integer convertidas:  COM_027
Colunas integer convertidas:  COM_028
Colunas integer convertidas:  COM_029
Colunas integer convertidas:  COM_030
Colunas integer convertidas:  COM_031
Colunas integer convertidas:  COM_032
Colunas integer convertidas:  COM_033
Colunas integer convertidas:  COM_034
Colunas integer convertidas:  COM_035
Colunas integer convertidas:  COM_036
Colunas integer convertidas:  COM_037
Colunas integer convertidas:  COM_038
Colunas integer convertidas:  COM_041
Colunas integer convertidas:  COM_042
Colunas integer convertidas:  COM_043
Colunas integer convertidas:  COM_044
Colunas integer convertidas:  COM_045
Colunas integer convertidas:  COM_046
Colunas integer convertidas:  COM_049
Colunas integer convertidas:  COM_050
Colunas integer convertidas:  COM_051
Colunas integer convertidas:  COM_052
Colunas integer convertidas:  COM_053
Colunas integer convertidas:  COM_054
Colunas integer convertidas:  COM_055
Colunas integer convertidas:  COM_056
Colunas integer convertidas:  COM_057
Colunas integer convertidas:  COM_058
Colunas float convertidas:  COM_039
Colunas float convertidas:  COM_040
Colunas float convertidas:  COM_047
Colunas float convertidas:  COM_048
Colunas float convertidas:  COM_059

In [22]:
#Tratamento, Limpeza e Conversão do tipo do dado
#Santa Cruz
#Conversão do Código da distribuidora para o CNPJ
df_comercial_santacruz_join['COM_001'] = df_comercial_santacruz_join['COM_001'].replace('69','53859112000169')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_comercial_santacruz_join[coluna_integer] = df_comercial_santacruz_join[coluna_integer].replace(np.nan,0).astype('int')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_comercial_santacruz_join[coluna_float] = df_comercial_santacruz_join[coluna_float].replace(np.nan,0).astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)

Colunas integer convertidas:  COM_005
Colunas integer convertidas:  COM_006
Colunas integer convertidas:  COM_007
Colunas integer convertidas:  COM_008
Colunas integer convertidas:  COM_009
Colunas integer convertidas:  COM_010
Colunas integer convertidas:  COM_011
Colunas integer convertidas:  COM_012
Colunas integer convertidas:  COM_013
Colunas integer convertidas:  COM_014
Colunas integer convertidas:  COM_015
Colunas integer convertidas:  COM_016
Colunas integer convertidas:  COM_017
Colunas integer convertidas:  COM_018
Colunas integer convertidas:  COM_019
Colunas integer convertidas:  COM_020
Colunas integer convertidas:  COM_021
Colunas integer convertidas:  COM_022
Colunas integer convertidas:  COM_023
Colunas integer convertidas:  COM_024
Colunas integer convertidas:  COM_025
Colunas integer convertidas:  COM_026
Colunas integer convertidas:  COM_027
Colunas integer convertidas:  COM_028
Colunas integer convertidas:  COM_029
Colunas integer convertidas:  COM_030
Colunas integer convertidas:  COM_031
Colunas integer convertidas:  COM_032
Colunas integer convertidas:  COM_033
Colunas integer convertidas:  COM_034
Colunas integer convertidas:  COM_035
Colunas integer convertidas:  COM_036
Colunas integer convertidas:  COM_037
Colunas integer convertidas:  COM_038
Colunas integer convertidas:  COM_041
Colunas integer convertidas:  COM_042
Colunas integer convertidas:  COM_043
Colunas integer convertidas:  COM_044
Colunas integer convertidas:  COM_045
Colunas integer convertidas:  COM_046
Colunas integer convertidas:  COM_049
Colunas integer convertidas:  COM_050
Colunas integer convertidas:  COM_051
Colunas integer convertidas:  COM_052
Colunas integer convertidas:  COM_053
Colunas integer convertidas:  COM_054
Colunas integer convertidas:  COM_055
Colunas integer convertidas:  COM_056
Colunas integer convertidas:  COM_057
Colunas integer convertidas:  COM_058
Colunas float convertidas:  COM_039
Colunas float convertidas:  COM_040
Colunas float convertidas:  COM_047
Colunas float convertidas:  COM_048
Colunas float convertidas:  COM_059

In [23]:
#Tratamento, Limpeza e Conversão do tipo do dado
#RGE
#Conversão do Código da distribuidora para o CNPJ
df_comercial_rge_join['COM_001'] = df_comercial_rge_join['COM_001'].replace('396','02016440000162')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_comercial_rge_join[coluna_integer] = df_comercial_rge_join[coluna_integer].replace(np.nan,0).astype('int')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_comercial_rge_join[coluna_float] = df_comercial_rge_join[coluna_float].replace(np.nan,0).astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)

Colunas integer convertidas:  COM_005
Colunas integer convertidas:  COM_006
Colunas integer convertidas:  COM_007
Colunas integer convertidas:  COM_008
Colunas integer convertidas:  COM_009
Colunas integer convertidas:  COM_010
Colunas integer convertidas:  COM_011
Colunas integer convertidas:  COM_012
Colunas integer convertidas:  COM_013
Colunas integer convertidas:  COM_014
Colunas integer convertidas:  COM_015
Colunas integer convertidas:  COM_016
Colunas integer convertidas:  COM_017
Colunas integer convertidas:  COM_018
Colunas integer convertidas:  COM_019
Colunas integer convertidas:  COM_020
Colunas integer convertidas:  COM_021
Colunas integer convertidas:  COM_022
Colunas integer convertidas:  COM_023
Colunas integer convertidas:  COM_024
Colunas integer convertidas:  COM_025
Colunas integer convertidas:  COM_026
Colunas integer convertidas:  COM_027
Colunas integer convertidas:  COM_028
Colunas integer convertidas:  COM_029
Colunas integer convertidas:  COM_030
Colunas integer convertidas:  COM_031
Colunas integer convertidas:  COM_032
Colunas integer convertidas:  COM_033
Colunas integer convertidas:  COM_034
Colunas integer convertidas:  COM_035
Colunas integer convertidas:  COM_036
Colunas integer convertidas:  COM_037
Colunas integer convertidas:  COM_038
Colunas integer convertidas:  COM_041
Colunas integer convertidas:  COM_042
Colunas integer convertidas:  COM_043
Colunas integer convertidas:  COM_044
Colunas integer convertidas:  COM_045
Colunas integer convertidas:  COM_046
Colunas integer convertidas:  COM_049
Colunas integer convertidas:  COM_050
Colunas integer convertidas:  COM_051
Colunas integer convertidas:  COM_052
Colunas integer convertidas:  COM_053
Colunas integer convertidas:  COM_054
Colunas integer convertidas:  COM_055
Colunas integer convertidas:  COM_056
Colunas integer convertidas:  COM_057
Colunas integer convertidas:  COM_058
Colunas float convertidas:  COM_039
Colunas float convertidas:  COM_040
Colunas float convertidas:  COM_047
Colunas float convertidas:  COM_048
Colunas float convertidas:  COM_059

# Validação de Municipio

In [24]:
#Validação de Municipio
#Paulista
#Define os municipios
municipios_paulista = chaves_paulista[['COM_002']].astype('str')
municipios_comercial_paulista = df_comercial_paulista[['COM_002']]

#Cruza os municipios existentes com os municipios do arquivo
municipios_paulista_join = municipios_paulista.merge(municipios_comercial_paulista,indicator=True,on='COM_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_paulista_join[municipios_paulista_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [COM_002, _merge]
Index: []

In [25]:
#Validação de Municipio
#Piratininga
#Define os municipios
municipios_piratininga = chaves_piratininga[['COM_002']].astype('str')
municipios_comercial_piratininga = df_comercial_piratininga[['COM_002']]

#Cruza os municipios existentes com os municipios do arquivo
municipios_piratininga_join = municipios_piratininga.merge(municipios_comercial_piratininga,indicator=True,on='COM_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_piratininga_join[municipios_piratininga_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [COM_002, _merge]
Index: []

In [26]:
#Validação de Municipio
#Santa Cruz
#Define os municipios
municipios_santacruz = chaves_santacruz[['COM_002']].astype('str')
municipios_comercial_santacruz = df_comercial_santacruz[['COM_002']]

#Cruza os municipios existentes com os municipios do arquivo
municipios_santacruz_join = municipios_santacruz.merge(municipios_comercial_santacruz,indicator=True,on='COM_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_santacruz_join[municipios_santacruz_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [COM_002, _merge]
Index: []

In [27]:
#Validação de Municipio
#RGE
#Define os municipios
municipios_rge = chaves_rge[['COM_002']].astype('str')
municipios_comercial_rge = df_comercial_rge[['COM_002']]

#Cruza os municipios existentes com os municipios do arquivo
municipios_rge_join = municipios_rge.merge(municipios_comercial_rge,indicator=True,on='COM_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_rge_join[municipios_rge_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [COM_002, _merge]
Index: []

# Validação de Regra ANEEL

In [28]:
#Número de Consumidores
#Paulista
linhas = range(len(df_comercial_paulista_join))
for linha in linhas:
    # Compara o número de consumidores ativos COM_005 com o número de consumidores ativos e faturados COM_006
    if df_comercial_paulista_join.loc[linha,'COM_005'] < df_comercial_paulista_join.loc[linha,'COM_006']:
        print('Erro na linha: ',linha+2,'\n',df_comercial_paulista_join.loc[linha,'COM_005'],df_comercial_paulista_join.loc[linha,'COM_006'])

In [29]:
#Número de Consumidores
#Piratininga
linhas = range(len(df_comercial_piratininga_join))
for linha in linhas:
    # Compara o número de consumidores ativos COM_005 com o número de consumidores ativos e faturados COM_006
    if df_comercial_piratininga_join.loc[linha,'COM_005'] < df_comercial_piratininga_join.loc[linha,'COM_006']:
        print('Erro na linha: ',linha+2,'\n',df_comercial_piratininga_join.loc[linha,'COM_005'],df_comercial_piratininga_join.loc[linha,'COM_006'])

In [30]:
#Número de Consumidores
#Santa Cruz
linhas = range(len(df_comercial_santacruz_join))
for linha in linhas:
    # Compara o número de consumidores ativos COM_005 com o número de consumidores ativos e faturados COM_006
    if df_comercial_santacruz_join.loc[linha,'COM_005'] < df_comercial_santacruz_join.loc[linha,'COM_006']:
        print('Erro na linha: ',linha+2,'\n',df_comercial_santacruz_join.loc[linha,'COM_005'],df_comercial_santacruz_join.loc[linha,'COM_006'])

In [31]:
#Número de Consumidores
#RGE
linhas = range(len(df_comercial_rge_join))
for linha in linhas:
    # Compara o número de consumidores ativos COM_005 com o número de consumidores ativos e faturados COM_006
    if df_comercial_rge_join.loc[linha,'COM_005'] < df_comercial_rge_join.loc[linha,'COM_006']:
        print('Erro na linha: ',linha+2,'\n',df_comercial_rge_join.loc[linha,'COM_005'],df_comercial_rge_join.loc[linha,'COM_006'])

# Exportação dos Dados

In [32]:
#Paulista
arquivo = 'COMERCIAL.csv'
df_comercial_paulista_join.to_csv(os.path.join(pasta_paulista,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')

In [33]:
#Piratininga
arquivo = 'COMERCIAL.csv'
df_comercial_piratininga_join.to_csv(os.path.join(pasta_piratininga,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')

In [34]:
#Santa Cruz
arquivo = 'COMERCIAL.csv'
df_comercial_santacruz_join.to_csv(os.path.join(pasta_santacruz,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')

In [35]:
#RGE
arquivo = 'COMERCIAL.csv'
df_comercial_rge_join.to_csv(os.path.join(pasta_rge,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')