In [1]:
#Bibliotecas
import pandas as pd
import numpy as np
import keyring
import cx_Oracle
import os
import glob
import math
import warnings
warnings.filterwarnings("ignore")

# Dados de Entrada

In [2]:
#Dados de entrada
#Pasta TEC_SUB para ano 2023
pasta = r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023'

#Chaves Primárias
chaves_paulista = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\TECSUB\INDGER2.0_TECSUB_Chaves.xlsx',sheet_name='Paulista')
chaves_piratininga = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\TECSUB\INDGER2.0_TECSUB_Chaves.xlsx',sheet_name='Piratininga')
chaves_santacruz = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\TECSUB\INDGER2.0_TECSUB_Chaves.xlsx',sheet_name='Santa Cruz')
chaves_rge = pd.read_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Chaves Primarias\TECSUB\INDGER2.0_TECSUB_Chaves.xlsx',sheet_name='RGE')

#Selecionar pasta do mes de referência
pasta_mes = input('Insira o mês (dois dígitos):')
ano = input('Insira o ano (4 dígitos):')
if pasta_mes == '01':
    mes = '01'
    pasta_mes = '01 - Janeiro\*'
    pasta_mes_paulista = '01 - Janeiro'
    pasta_mes_piratininga = '01 - Janeiro'
    pasta_mes_santacruz = '01 - Janeiro'
    pasta_mes_rge = '01 - Janeiro'
    print(pasta_mes)
elif pasta_mes == '02':
    mes = '02'
    pasta_mes = '02 - Fevereiro\*'
    pasta_mes_paulista = '02 - Fevereiro'
    pasta_mes_piratininga = '02 - Fevereiro'
    pasta_mes_santacruz = '02 - Fevereiro'
    pasta_mes_rge = '02 - Fevereiro'
    print(pasta_mes)
elif pasta_mes == '03':
    mes = '03'
    pasta_mes = '03 - Março\*'
    pasta_mes_paulista = '03 - Março'
    pasta_mes_piratininga = '03 - Março'
    pasta_mes_santacruz = '03 - Março'
    pasta_mes_rge = '03 - Março'
    print(pasta_mes)
elif pasta_mes == '04':
    mes = '04'
    pasta_mes = '04 - Abril\*'
    pasta_mes_paulista = '04 - Abril'
    pasta_mes_piratininga = '04 - Abril'
    pasta_mes_santacruz = '04 - Abril'
    pasta_mes_rge = '04 - Abril'
    print(pasta_mes)
elif pasta_mes == '05':
    mes = '05'
    pasta_mes = '05 - Maio\*'
    pasta_mes_paulista = '05 - Maio'
    pasta_mes_piratininga = '05 - Maio'
    pasta_mes_santacruz = '05 - Maio'
    pasta_mes_rge = '05 - Maio'
    print(pasta_mes)
elif pasta_mes == '06':
    mes = '06'
    pasta_mes = '06 - Junho\*'
    pasta_mes_paulista = '06 - Junho'
    pasta_mes_piratininga = '06 - Junho'
    pasta_mes_santacruz = '06 - Junho'
    pasta_mes_rge = '06 - Junho'
    print(pasta_mes)
elif pasta_mes == '07':
    mes = '07'
    pasta_mes = '07 - Julho\*'
    pasta_mes_paulista = '07 - Julho'
    pasta_mes_piratininga = '07 - Julho'
    pasta_mes_santacruz = '07 - Julho'
    pasta_mes_rge = '07 - Julho'
    print(pasta_mes)
elif pasta_mes == '08':
    mes = '08'
    pasta_mes = '08 - Agosto\*'
    pasta_mes_paulista = '08 - Agosto'
    pasta_mes_piratininga = '08 - Agosto'
    pasta_mes_santacruz = '08 - Agosto'
    pasta_mes_rge = '08 - Agosto'
    print(pasta_mes)
elif pasta_mes == '09':
    mes = '09'
    pasta_mes = '09 - Setembro\*'
    pasta_mes_paulista = '09 - Setembro'
    pasta_mes_piratininga = '09 - Setembro'
    pasta_mes_santacruz = '09 - Setembro'
    pasta_mes_rge = '09 - Setembro'
    print(pasta_mes)
elif pasta_mes == '10':
    mes = '10'
    pasta_mes = '10 - Outubro\*'
    pasta_mes_paulista = '10 - Outubro'
    pasta_mes_piratininga = '10 - Outubro'
    pasta_mes_santacruz = '10 - Outubro'
    pasta_mes_rge = '10 - Outubro'
    print(pasta_mes)
elif pasta_mes == '11':
    mes = '11'
    pasta_mes = '11 - Novembro\*'
    pasta_mes_paulista = '11 - Novembro'
    pasta_mes_piratininga = '11 - Novembro'
    pasta_mes_santacruz = '11 - Novembro'
    pasta_mes_rge = '11 - Novembro'
    print(pasta_mes)
elif pasta_mes == '12':
    mes = '12'
    pasta_mes = '12 - Dezembro\*'
    pasta_mes_paulista = '12 - Dezembro'
    pasta_mes_piratininga = '12 - Dezembro'
    pasta_mes_santacruz = '12 - Dezembro'
    pasta_mes_rge = '12 - Dezembro'
    print(pasta_mes)
else:
    print('Mês Inválido')
    
#Pasta onde está os arquivos    
diretorio = os.path.join(pasta,pasta_mes)
arquivos = glob.glob(diretorio)

#Define o diretorio onde será salvo os arquivos consolidados
pasta_paulista = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\1 - Paulista\\2023\\{pasta_mes_paulista}\\2 - Arquivos Consolidados'
pasta_piratininga = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\2 - Piratininga\\2023\\{pasta_mes_piratininga}\\2 - Arquivos Consolidados'
pasta_santacruz = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\3 - Santa Cruz\\2023\\{pasta_mes_santacruz}\\2 - Arquivos Consolidados'
pasta_rge = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\4 - RGE\\2023\\{pasta_mes_rge}\\2 - Arquivos Consolidados'
pasta_paulista_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\1 - Paulista\\2023\\{pasta_mes_paulista}\\1 - Status'
pasta_piratininga_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\2 - Piratininga\\2023\\{pasta_mes_piratininga}\\1 - Status'
pasta_santacruz_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\3 - Santa Cruz\\2023\\{pasta_mes_santacruz}\\1 - Status'
pasta_rge_status = f'C:\\Users\\2018459\\CPFL Energia S A\\INDIGER - INDGER\\RRR\\02 - Dados\\4 - RGE\\2023\\{pasta_mes_rge}\\1 - Status'

Insira o mês (dois dígitos):10
Insira o ano (4 dígitos):2023
10 - Outubro\*

In [3]:
#Colunas
colunas_tecsub = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_006','TECSUB_007','TECSUB_008','TECSUB_009','TECSUB_010','TECSUB_011','TECSUB_012','TECSUB_013','TECSUB_014','TECSUB_015','TECSUB_016']
colunas_campos = ['TECSUB_006','TECSUB_007','TECSUB_008','TECSUB_009','TECSUB_010','TECSUB_011','TECSUB_012','TECSUB_013','TECSUB_014','TECSUB_015','TECSUB_016']
colunas_chaves = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005']
colunas_integer = ['TECSUB_002','TECSUB_006','TECSUB_007','TECSUB_008','TECSUB_009','TECSUB_010','TECSUB_011','TECSUB_012','TECSUB_013','TECSUB_014','TECSUB_015']
colunas_float = ['TECSUB_016']
colunas_string = ['TECSUB_005']
colunas_mes = ['TECSUB_008','TECSUB_009','TECSUB_010','TECSUB_011','TECSUB_012','TECSUB_013','TECSUB_014','TECSUB_015']
colunas_djtv = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_014','TECSUB_015']
colunas_dpt = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_014','TECSUB_015']
colunas_drt = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_006','TECSUB_008','TECSUB_009','TECSUB_010','TECSUB_011','TECSUB_012','TECSUB_013','TECSUB_014','TECSUB_015']
colunas_rcc = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_007']
colunas_regd = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_006']
colunas_regm = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_008','TECSUB_009','TECSUB_010','TECSUB_011','TECSUB_012','TECSUB_013']
colunas_ropt = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_016']
colunas_ros = ['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005','TECSUB_016']
listas_arquivos = ['TECSUB_DJTV_HelesPires','TECSUB_DPT_FabioRochaCavalcante','TECSUB_DRT_DiegoPereiraSoares','TECSUB_RCC_DouglasAlves','TECSUB_REGD_EduardoDiasCarvalho','TECSUB_REGM_PedroAntonioPereira','TECSUB_ROPT_PaulaMitiko','TECSUB_ROS_CristianoGattermann']

#Layout com todas as colunas
layout_tecsub_colunas = pd.DataFrame(data = [],columns = colunas_tecsub)

#Tabela TECSUB
tabela_tecsub = []

#Duplicadas
df_duplicadas = pd.DataFrame(data = [],columns = colunas_tecsub)

#Total de arquivos esperados na pasta
arquivos_total = 8

#Quantidade de arquivos submetidos
arquivos_submetidos = len(arquivos)

#Arquivos faltantes
print('Arquivos faltantes:',(arquivos_total-arquivos_submetidos))

#Flag para mostrar os arquivos faltantes
flag_faltantes = []

#Leitura dos arquivos
for arquivo in arquivos:
    try:
        #Lê o arquivo na pasta
        df_tecsub = pd.read_excel(arquivo,sheet_name='TEC_SUB', decimal=',')
        
        #Define o mês e o ano
        linhas_df_tecsub = range(len(df_tecsub.index))
        df_tecsub['TECSUB_003'] = df_tecsub['TECSUB_003'].astype('str')
        for linha in linhas_df_tecsub:
            df_tecsub.loc[linha,'TECSUB_003'] = df_tecsub.loc[linha,'TECSUB_003'].zfill(2)
        df_tecsub['TECSUB_004'] = ano
        
        #Valida se foi enviado algum mês fora do mês de referência
        flag_mes = 0
        for linha in linhas_df_tecsub:
            if df_tecsub.loc[linha,'TECSUB_003'] != mes:
                flag_mes = 1
        if flag_mes != 0:
            print('MÊS INCORRETO!!!', arquivo)
            
        #Valida se foi enviado algum código da distribuidora incorreto
        flag_distribuidora = 0
        for linha in linhas_df_tecsub:
            if df_tecsub.loc[linha,'TECSUB_001'] not in [63,2937,69,396]:
                flag_distribuidora = 1
        if flag_distribuidora != 0:
            print('DISTRIBUIDORA INCORRETA!!!', arquivo)
        
        #Converte as chave para string
        for coluna in colunas_chaves:
            df_tecsub[coluna] = df_tecsub[coluna].replace(np.nan,'0').astype('str')
        
        #Empilha as chaves primárias duplicadas
        if df_tecsub.duplicated(subset=['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005']).any() == False:
            pass
        else:
            duplicadas = df_tecsub[df_tecsub.duplicated(subset=['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005'],keep=False)]
            df_duplicadas = df_duplicadas.append(duplicadas,ignore_index=True)
        
        #Empilha todos os arquivos
        layout_tecsub_colunas = layout_tecsub_colunas.append(df_tecsub,ignore_index=True)
        
        #Validação de colunas dos arquivos
        if 'TECSUB_DJTV' in arquivo:
            df_tecsub.columns == colunas_djtv
            print(arquivo)
            flag_faltantes.append('TECSUB_DJTV_HelesPires')
        elif 'TECSUB_DPT' in arquivo:
            df_tecsub.columns == colunas_dpt
            print(arquivo)
            flag_faltantes.append('TECSUB_DPT_FabioRochaCavalcante')
        elif 'TECSUB_DRT' in arquivo:
            df_tecsub.columns == colunas_drt
            print(arquivo)
            flag_faltantes.append('TECSUB_DRT_DiegoPereiraSoares')
        elif 'TECSUB_RCC' in arquivo:
            df_tecsub.columns == colunas_rcc
            print(arquivo)
            flag_faltantes.append('TECSUB_RCC_DouglasAlves')
        elif 'TECSUB_REGD' in arquivo:
            df_tecsub.columns == colunas_regd
            print(arquivo)
            flag_faltantes.append('TECSUB_REGD_EduardoDiasCarvalho')
        elif 'TECSUB_REGM' in arquivo:
            df_tecsub.columns == colunas_regm
            print(arquivo)
            flag_faltantes.append('TECSUB_REGM_PedroAntonioPereira')
        elif 'TECSUB_ROPT' in arquivo:
            df_tecsub.columns == colunas_ropt
            print(arquivo)
            flag_faltantes.append('TECSUB_ROPT_PaulaMitiko')
        elif 'TECSUB_ROS' in arquivo:
            df_tecsub.columns == colunas_ros
            print(arquivo)
            flag_faltantes.append('TECSUB_ROS_CristianoGattermann')
        else:
            print('Arquivo com colunas divergentes',arquivo)
            
        
    except Exception as err:
        print('Arquivo com erro:',err)

        
#Exclui as linhas duplicadas
df_duplicadas = df_duplicadas.drop_duplicates(ignore_index=True)

#Compara se há chaves primárias duplicadas
if df_duplicadas.duplicated(subset=['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005']).any() == False:
    print('Não há chaves duplicadas')
else:
    print('Há chaves duplicadas', arquivo)
    #Mostra as chaves duplicadas
    df_duplicadas = df_duplicadas[df_duplicadas.duplicated(subset=['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005'],keep=False)]
    df_duplicadas.to_excel(r'C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\RRR\02 - Dados\Erros Duplicadas\duplicadas_tecsub.xlsx')
    display(df_duplicadas)


#Reporta os arquivos faltantes
for lista_arquivos in listas_arquivos:
    if lista_arquivos not in flag_faltantes:
        print(f'Arquivo faltante: {lista_arquivos}')

Arquivos faltantes: 0
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_DJTV_HelesPires_10_2023.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_DPT_MarcioRogerioLopesJunior_10_2023.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_DRT_DiegoPereiraSoares.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_RCCP_AndreBenincasa_10_2023.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_REGD_EduardoDiasCarvalho.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_REGM_PedroAntonioPereira.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_ROPT_PaulaMitiko.xlsx
C:\Users\2018459\CPFL Energia S A\INDIGER - INDGER\INDGER 2.0\TEC_SUB\2023\10 - Outubro\TECSUB_ROS_CristianoGattermann.xlsx
Não há chaves duplicadas

In [4]:
#Dropa as linhas duplicadas
layout_tecsub_colunas = layout_tecsub_colunas.drop_duplicates(ignore_index=True)

#Empilha os dataframe
tabela_tecsub = layout_tecsub_colunas.groupby(['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004','TECSUB_005'],as_index=False).max()
print('Dados empilhados')

Dados empilhados

In [5]:
#Define o mês e o ano
linhas = range(len(tabela_tecsub.index))
tabela_tecsub['TECSUB_003'] = tabela_tecsub['TECSUB_003'].astype('str')
for linha in linhas:
    tabela_tecsub.loc[linha,'TECSUB_003'] = tabela_tecsub.loc[linha,'TECSUB_003'].zfill(2)
tabela_tecsub['TECSUB_004'] = ano

In [6]:
display(tabela_tecsub)

,TECSUB_001,TECSUB_002,TECSUB_003,TECSUB_004,TECSUB_005,TECSUB_006,TECSUB_007,TECSUB_008,TECSUB_009,TECSUB_010,TECSUB_011,TECSUB_012,TECSUB_013,TECSUB_014,TECSUB_015,TECSUB_016
0,2937,13480,10,2023,BOQ,36608.0,68.0,10.0,2023.0,8.0,2023.0,10.0,2023.0,10.0,2023.0,84.166667
1,2937,13482,10,2023,CLI,35432.0,1302.0,10.0,2023.0,10.0,2022.0,9.0,2023.0,7.0,2023.0,87.456719
2,2937,13483,10,2023,CUB,18386.0,385.0,10.0,2023.0,8.0,2023.0,10.0,2023.0,9.0,2023.0,98.215317
3,2937,13483,10,2023,HBO,5813.0,63.0,10.0,2023.0,10.0,2023.0,10.0,2023.0,10.0,2023.0,98.312588
4,2937,13483,10,2023,PAS,451.0,28.0,10.0,2023.0,10.0,2023.0,10.0,2023.0,9.0,2023.0,77.531008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,69,2922,10,2023,ROS,3118.0,108.0,10.0,2023.0,5.0,2023.0,8.0,2023.0,1.0,2022.0,61.197997
709,69,2922,10,2023,SED,620.0,69.0,10.0,2023.0,6.0,2023.0,8.0,2023.0,1.0,2023.0,62.500000
710,69,964,10,2023,MCB,NaN,NaN,10.0,2023.0,6.0,2023.0,4.0,2022.0,1.0,2022.0,0.000000
711,69,964,10,2023,PDA,20290.0,1248.0,10.0,2023.0,6.0,2023.0,8.0,2023.0,1.0,2023.0,74.288870
712,69,964,10,2023,UBF,1.0,NaN,10.0,2023.0,6.0,2023.0,11.0,2022.0,9.0,2021.0,1.102725

In [7]:
#Verifica se há chaves nulas
tabela_tecsub = tabela_tecsub.replace('nan',np.nan)

for coluna in colunas_chaves:
    if tabela_tecsub[coluna].isnull().any() == True:
        print('Existe Chave Primária Nula: ',coluna)

In [8]:
#Define o mês e o ano das Chaves Primárias
chaves_paulista['TECSUB_003'] = int(mes)
chaves_piratininga['TECSUB_003'] = int(mes)
chaves_santacruz['TECSUB_003'] = int(mes)
chaves_rge['TECSUB_003'] = int(mes)
chaves_paulista['TECSUB_004'] = int(ano)
chaves_piratininga['TECSUB_004'] = int(ano)
chaves_santacruz['TECSUB_004'] = int(ano)
chaves_rge['TECSUB_004'] = int(ano)

#Seleciona somente as colunas das chaves primárias
chaves_paulista = chaves_paulista[['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004']]
chaves_piratininga = chaves_piratininga[['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004']]
chaves_santacruz = chaves_santacruz[['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004']]
chaves_rge = chaves_rge[['TECSUB_001','TECSUB_002','TECSUB_003','TECSUB_004']]

# Validação de Dados

In [9]:
# Validação de número negativo
try:
    for coluna in colunas_campos:
        if tabela_tecsub[coluna].min() < 0:
            print('Temos dados negativos:',coluna)

except:
    print('Erro na coluna:',coluna)

In [10]:
#Define as linhas do dataframe
linhas_tecsub = range(len(tabela_tecsub.index))

#Validação do percentual de carregamento
for linha_tecsub in linhas_tecsub:
    if tabela_tecsub.loc[linha_tecsub,'TECSUB_016'] > 100:
        print('Valor inválido',tabela_tecsub.loc[linha_tecsub,'TECSUB_016'])

Valor inválido 100.26097301136363
Valor inválido 101.168
Valor inválido 113.11428571428573
Valor inválido 101.32833333333333
Valor inválido 119.41250000000001
Valor inválido 122.35199999999999
Valor inválido 112.328
Valor inválido 105.74933333333334
Valor inválido 100.54204317269078
Valor inválido 100.2750161536654

In [11]:
#Separa a tabela por distribuidora para verificar se há colunas nulas
df_tecsub_paulista = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '63']
df_tecsub_piratininga = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '2937']
df_tecsub_santacruz = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '69']
df_tecsub_rge = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '396']

In [12]:
# PAULISTA 
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_paulista=[]
for coluna in df_tecsub_paulista.columns:
    if df_tecsub_paulista[coluna].isnull().all():
        indicadores_nao_recebidos_paulista.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_tecsub, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_paulista))

status_recebimento_tecsub_paulista = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_tecsub_paulista.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_tecsub_paulista = status_recebimento_tecsub_paulista.reindex(columns = ['Indicador','Status'])
status_recebimento_tecsub_paulista.insert(loc=2,column='Distribuidora',value='Paulista')
status_recebimento_tecsub_paulista.to_excel(os.path.join(pasta_paulista_status,'status_recebimento_tecsub_paulista.xlsx'))
status_recebimento_tecsub_paulista

     Indicador  Status Distribuidora
0   TECSUB_001    True      Paulista
1   TECSUB_002    True      Paulista
2   TECSUB_003    True      Paulista
3   TECSUB_004    True      Paulista
4   TECSUB_005    True      Paulista
5   TECSUB_006    True      Paulista
6   TECSUB_007    True      Paulista
7   TECSUB_008    True      Paulista
8   TECSUB_009    True      Paulista
9   TECSUB_010    True      Paulista
10  TECSUB_011    True      Paulista
11  TECSUB_012    True      Paulista
12  TECSUB_013    True      Paulista
13  TECSUB_014    True      Paulista
14  TECSUB_015    True      Paulista
15  TECSUB_016    True      Paulista

In [13]:
# Piratininga 
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_piratininga=[]
for coluna in df_tecsub_piratininga.columns:
    if df_tecsub_piratininga[coluna].isnull().all():
        indicadores_nao_recebidos_piratininga.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_tecsub, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_piratininga))

status_recebimento_tecsub_piratininga = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_tecsub_piratininga.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_tecsub_piratininga = status_recebimento_tecsub_piratininga.reindex(columns = ['Indicador','Status'])
status_recebimento_tecsub_piratininga.insert(loc=2,column='Distribuidora',value='Piratininga')
status_recebimento_tecsub_piratininga.to_excel(os.path.join(pasta_piratininga_status,'status_recebimento_tecsub_piratininga.xlsx'))
status_recebimento_tecsub_piratininga

     Indicador  Status Distribuidora
0   TECSUB_001    True   Piratininga
1   TECSUB_002    True   Piratininga
2   TECSUB_003    True   Piratininga
3   TECSUB_004    True   Piratininga
4   TECSUB_005    True   Piratininga
5   TECSUB_006    True   Piratininga
6   TECSUB_007    True   Piratininga
7   TECSUB_008    True   Piratininga
8   TECSUB_009    True   Piratininga
9   TECSUB_010    True   Piratininga
10  TECSUB_011    True   Piratininga
11  TECSUB_012    True   Piratininga
12  TECSUB_013    True   Piratininga
13  TECSUB_014    True   Piratininga
14  TECSUB_015    True   Piratininga
15  TECSUB_016    True   Piratininga

In [14]:
# Santa Cruz 
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_santacruz=[]
for coluna in df_tecsub_santacruz.columns:
    if df_tecsub_santacruz[coluna].isnull().all():
        indicadores_nao_recebidos_santacruz.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_tecsub, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_santacruz))

status_recebimento_tecsub_santacruz = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_tecsub_santacruz.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_tecsub_santacruz = status_recebimento_tecsub_santacruz.reindex(columns = ['Indicador','Status'])
status_recebimento_tecsub_santacruz.insert(loc=2,column='Distribuidora',value='Santa Cruz')
status_recebimento_tecsub_santacruz.to_excel(os.path.join(pasta_santacruz_status,'status_recebimento_tecsub_santacruz.xlsx'))
status_recebimento_tecsub_santacruz

     Indicador  Status Distribuidora
0   TECSUB_001    True    Santa Cruz
1   TECSUB_002    True    Santa Cruz
2   TECSUB_003    True    Santa Cruz
3   TECSUB_004    True    Santa Cruz
4   TECSUB_005    True    Santa Cruz
5   TECSUB_006    True    Santa Cruz
6   TECSUB_007    True    Santa Cruz
7   TECSUB_008    True    Santa Cruz
8   TECSUB_009    True    Santa Cruz
9   TECSUB_010    True    Santa Cruz
10  TECSUB_011    True    Santa Cruz
11  TECSUB_012    True    Santa Cruz
12  TECSUB_013    True    Santa Cruz
13  TECSUB_014    True    Santa Cruz
14  TECSUB_015    True    Santa Cruz
15  TECSUB_016    True    Santa Cruz

In [15]:
# RGE
# Filtra todas as colunas que não foram recebidas
indicadores_nao_recebidos_rge=[]
for coluna in df_tecsub_rge.columns:
    if df_tecsub_rge[coluna].isnull().all():
        indicadores_nao_recebidos_rge.append(coluna)

# Mostra todos os indicadores que não foram recebidos        
colunas = pd.DataFrame(colunas_tecsub, columns = ['NOME_COLUNAS'])
recebimento = (~colunas.isin(indicadores_nao_recebidos_rge))

status_recebimento_tecsub_rge = pd.merge(recebimento, colunas, left_index = True, right_index = True)

status_recebimento_tecsub_rge.rename(columns = {'NOME_COLUNAS_x':'Status', 'NOME_COLUNAS_y':'Indicador'},inplace = True)
status_recebimento_tecsub_rge = status_recebimento_tecsub_rge.reindex(columns = ['Indicador','Status'])
status_recebimento_tecsub_rge.insert(loc=2,column='Distribuidora',value='RGE')
status_recebimento_tecsub_rge.to_excel(os.path.join(pasta_rge_status,'status_recebimento_tecsub_rge.xlsx'))
status_recebimento_tecsub_rge

     Indicador  Status Distribuidora
0   TECSUB_001    True           RGE
1   TECSUB_002    True           RGE
2   TECSUB_003    True           RGE
3   TECSUB_004    True           RGE
4   TECSUB_005    True           RGE
5   TECSUB_006    True           RGE
6   TECSUB_007    True           RGE
7   TECSUB_008    True           RGE
8   TECSUB_009    True           RGE
9   TECSUB_010    True           RGE
10  TECSUB_011    True           RGE
11  TECSUB_012    True           RGE
12  TECSUB_013    True           RGE
13  TECSUB_014    True           RGE
14  TECSUB_015    True           RGE
15  TECSUB_016    True           RGE

In [16]:
#Separa a tabela por distribuidora para cruzar com as chaves primárias
df_tecsub_paulista = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '63']
df_tecsub_piratininga = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '2937']
df_tecsub_santacruz = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '69']
df_tecsub_rge = tabela_tecsub.loc[tabela_tecsub['TECSUB_001'] == '396']

In [17]:
#Define os dataframe
df_tecsub_paulista_join = df_tecsub_paulista
df_tecsub_piratininga_join = df_tecsub_piratininga 
df_tecsub_santacruz_join = df_tecsub_santacruz
df_tecsub_rge_join = df_tecsub_rge

# Tratamento, Limpeza e Conversão

In [18]:
#Tratamento, Limpeza e Conversão do tipo do dado
#Paulista
#Conversão do Código da distribuidora para o CNPJ
df_tecsub_paulista_join['TECSUB_001'] = df_tecsub_paulista_join['TECSUB_001'].replace('63','33050196000188')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_tecsub_paulista_join[coluna_integer] = df_tecsub_paulista_join[coluna_integer].replace(np.nan,0).astype('Int64')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_tecsub_paulista_join[coluna_float] = df_tecsub_paulista_join[coluna_float].astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)
        
for coluna_string in colunas_string:
    try:
        df_tecsub_paulista_join[coluna_string] = df_tecsub_paulista_join[coluna_string].astype('str')
        print('Colunas string convertidas: ',coluna_string)
    except:
        print('Não foi possível converter a coluna string: ',coluna_string)

Colunas integer convertidas:  TECSUB_002
Colunas integer convertidas:  TECSUB_006
Colunas integer convertidas:  TECSUB_007
Colunas integer convertidas:  TECSUB_008
Colunas integer convertidas:  TECSUB_009
Colunas integer convertidas:  TECSUB_010
Colunas integer convertidas:  TECSUB_011
Colunas integer convertidas:  TECSUB_012
Colunas integer convertidas:  TECSUB_013
Colunas integer convertidas:  TECSUB_014
Colunas integer convertidas:  TECSUB_015
Colunas float convertidas:  TECSUB_016
Colunas string convertidas:  TECSUB_005

In [19]:
#Tratamento, Limpeza e Conversão do tipo do dado
#Piratininga
#Conversão do Código da distribuidora para o CNPJ
df_tecsub_piratininga_join['TECSUB_001'] = df_tecsub_piratininga_join['TECSUB_001'].replace('2937','04172213000151')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_tecsub_piratininga_join[coluna_integer] = df_tecsub_piratininga_join[coluna_integer].replace(np.nan,0).astype('Int64')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_tecsub_piratininga_join[coluna_float] = df_tecsub_piratininga_join[coluna_float].astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)
        
for coluna_string in colunas_string:
    try:
        df_tecsub_piratininga_join[coluna_string] = df_tecsub_piratininga_join[coluna_string].astype('str')
        print('Colunas string convertidas: ',coluna_string)
    except:
        print('Não foi possível converter a coluna string: ',coluna_string)

Colunas integer convertidas:  TECSUB_002
Colunas integer convertidas:  TECSUB_006
Colunas integer convertidas:  TECSUB_007
Colunas integer convertidas:  TECSUB_008
Colunas integer convertidas:  TECSUB_009
Colunas integer convertidas:  TECSUB_010
Colunas integer convertidas:  TECSUB_011
Colunas integer convertidas:  TECSUB_012
Colunas integer convertidas:  TECSUB_013
Colunas integer convertidas:  TECSUB_014
Colunas integer convertidas:  TECSUB_015
Colunas float convertidas:  TECSUB_016
Colunas string convertidas:  TECSUB_005

In [20]:
#Tratamento, Limpeza e Conversão do tipo do dado
#Santa Cruz
#Conversão do Código da distribuidora para o CNPJ
df_tecsub_santacruz_join['TECSUB_001'] = df_tecsub_santacruz_join['TECSUB_001'].replace('69','53859112000169')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_tecsub_santacruz_join[coluna_integer] = df_tecsub_santacruz_join[coluna_integer].replace(np.nan,0).astype('Int64')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_tecsub_santacruz_join[coluna_float] = df_tecsub_santacruz_join[coluna_float].astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)
        
for coluna_string in colunas_string:
    try:
        df_tecsub_santacruz_join[coluna_string] = df_tecsub_santacruz_join[coluna_string].astype('str')
        print('Colunas string convertidas: ',coluna_string)
    except:
        print('Não foi possível converter a coluna string: ',coluna_string)

Colunas integer convertidas:  TECSUB_002
Colunas integer convertidas:  TECSUB_006
Colunas integer convertidas:  TECSUB_007
Colunas integer convertidas:  TECSUB_008
Colunas integer convertidas:  TECSUB_009
Colunas integer convertidas:  TECSUB_010
Colunas integer convertidas:  TECSUB_011
Colunas integer convertidas:  TECSUB_012
Colunas integer convertidas:  TECSUB_013
Colunas integer convertidas:  TECSUB_014
Colunas integer convertidas:  TECSUB_015
Colunas float convertidas:  TECSUB_016
Colunas string convertidas:  TECSUB_005

In [21]:
#Tratamento, Limpeza e Conversão do tipo do dado
#RGE
#Conversão do Código da distribuidora para o CNPJ
df_tecsub_rge_join['TECSUB_001'] = df_tecsub_rge_join['TECSUB_001'].replace('396','02016440000162')

#Tratamento, Limpeza e Conversão dos dados
for coluna_integer in colunas_integer:
    try:
        df_tecsub_rge_join[coluna_integer] = df_tecsub_rge_join[coluna_integer].replace(np.nan,0).astype('Int64')
        print('Colunas integer convertidas: ',coluna_integer)
    except:
        print('Não foi possível converter a coluna integer: ',coluna_integer)
        
for coluna_float in colunas_float:
    try:
        df_tecsub_rge_join[coluna_float] = df_tecsub_rge_join[coluna_float].astype('float')
        print('Colunas float convertidas: ',coluna_float)
    except:
        print('Não foi possível converter a coluna float: ',coluna_float)
        
for coluna_string in colunas_string:
    try:
        df_tecsub_rge_join[coluna_string] = df_tecsub_rge_join[coluna_string].astype('str')
        print('Colunas string convertidas: ',coluna_string)
    except:
        print('Não foi possível converter a coluna string: ',coluna_string)

Colunas integer convertidas:  TECSUB_002
Colunas integer convertidas:  TECSUB_006
Colunas integer convertidas:  TECSUB_007
Colunas integer convertidas:  TECSUB_008
Colunas integer convertidas:  TECSUB_009
Colunas integer convertidas:  TECSUB_010
Colunas integer convertidas:  TECSUB_011
Colunas integer convertidas:  TECSUB_012
Colunas integer convertidas:  TECSUB_013
Colunas integer convertidas:  TECSUB_014
Colunas integer convertidas:  TECSUB_015
Colunas float convertidas:  TECSUB_016
Colunas string convertidas:  TECSUB_005

In [22]:
#Tratamento do mês (não podemos ter mês 0)
for coluna in colunas_mes:
    df_tecsub_paulista_join[coluna] = df_tecsub_paulista_join[coluna].replace(0,np.nan)
    df_tecsub_piratininga_join[coluna] = df_tecsub_piratininga_join[coluna].replace(0,np.nan)
    df_tecsub_santacruz_join[coluna] = df_tecsub_santacruz_join[coluna].replace(0,np.nan)
    df_tecsub_rge_join[coluna] = df_tecsub_rge_join[coluna].replace(0,np.nan)

# Validação por Conjunto

In [23]:
#Validação de Municipio
#Paulista
#Define os municipios
municipios_paulista = chaves_paulista[['TECSUB_002']].astype('int')
municipios_tecsub_paulista = df_tecsub_paulista[['TECSUB_002']]

#Dropa os municipios repetidos
municipios_tecsub_paulista = municipios_tecsub_paulista.drop_duplicates(ignore_index=True)

#Cruza os municipios existentes com os municipios do arquivo
municipios_paulista_join = municipios_paulista.merge(municipios_tecsub_paulista,indicator=True,on='TECSUB_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_paulista_join[municipios_paulista_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [TECSUB_002, _merge]
Index: []

In [24]:
#Validação de Municipio
#Piratininga
#Define os municipios
municipios_piratininga = chaves_piratininga[['TECSUB_002']].astype('int')
municipios_tecsub_piratininga = df_tecsub_piratininga[['TECSUB_002']]

#Dropa os municipios repetidos
municipios_tecsub_piratininga = municipios_tecsub_piratininga.drop_duplicates(ignore_index=True)

#Cruza os municipios existentes com os municipios do arquivo
municipios_piratininga_join = municipios_piratininga.merge(municipios_tecsub_piratininga,indicator=True,on='TECSUB_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_piratininga_join[municipios_piratininga_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [TECSUB_002, _merge]
Index: []

In [25]:
#Validação de Municipio
#Santa Cruz
#Define os municipios
municipios_santacruz = chaves_santacruz[['TECSUB_002']].astype('int')
municipios_tecsub_santacruz = df_tecsub_santacruz[['TECSUB_002']]

#Dropa os municipios repetidos
municipios_tecsub_santacruz = municipios_tecsub_santacruz.drop_duplicates(ignore_index=True)

#Cruza os municipios existentes com os municipios do arquivo
municipios_santacruz_join = municipios_santacruz.merge(municipios_tecsub_santacruz,indicator=True,on='TECSUB_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_santacruz_join[municipios_santacruz_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [TECSUB_002, _merge]
Index: []

In [26]:
#Validação de Municipio
#RGE
#Define os municipios
municipios_rge = chaves_rge[['TECSUB_002']].astype('int')
municipios_tecsub_rge = df_tecsub_rge[['TECSUB_002']]

#Dropa os municipios repetidos
municipios_tecsub_rge = municipios_tecsub_rge.drop_duplicates(ignore_index=True)

#Cruza os municipios existentes com os municipios do arquivo
municipios_rge_join = municipios_rge.merge(municipios_tecsub_rge,indicator=True,on='TECSUB_002',how='outer')

#Filtramos somente os municipios divergentes recebidos das áreas
municipios_rge_join[municipios_rge_join['_merge'] == 'right_only']

Empty DataFrame
Columns: [TECSUB_002, _merge]
Index: []

# Exportação dos Dados

In [27]:
#Paulista
arquivo = 'TEC_SUB.csv'
df_tecsub_paulista_join.to_csv(os.path.join(pasta_paulista,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')

In [28]:
#Piratininga
arquivo = 'TEC_SUB.csv'
df_tecsub_piratininga_join.to_csv(os.path.join(pasta_piratininga,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')

In [29]:
#Santa Cruz
arquivo = 'TEC_SUB.csv'
df_tecsub_santacruz_join.to_csv(os.path.join(pasta_santacruz,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')

In [30]:
#RGE
arquivo = 'TEC_SUB.csv'
df_tecsub_rge_join.to_csv(os.path.join(pasta_rge,arquivo), sep=';',index=False, float_format = '%.4f', decimal=',')